# Generated by Django 3.1.3 on 2020-11-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
